Added check routine for action variables

diff --git a/.github/workflows/build.docker.images.yml b/.github/workflows/build.docker.images.yml
--- a/.github/workflows/build.docker.images.yml
+++ b/.github/workflows/build.docker.images.yml
@@ -19,8 +19,30 @@ env:
   REGISTRY_PLATFORMS: ${{ vars.REGISTRY_PLATFORMS }}
 
 jobs:
-  setup-build-push:
+  requirments:
+    name: Requirments
     runs-on: ubuntu-latest
+
+    strategy:
+      fail-fast: false
+      matrix:
+        vars: [REGISTRY, REGISTRY_ACCOUNT, REGISTRY_REPO, REGISTRY_REPO_TAG_CACHE_NAME, REGISTRY_PLATFORMS]
+          
+    steps:
+      - name: Check if variable exist
+        run: |         
+          if [[ -z ${!VARNAME} ]]; then
+            echo "Variable \"${VARNAME}\" not found. Please create the variable under \"Repository variables\" \(https://github.com/${{ github.REPOSITORY}}/settings/variables/actions\)."
+            exit 1
+          fi
+        env:
+          VARNAME: "${{ matrix.vars }}"
+
+  setup-build-push:
+    name: Docker build & push
+    runs-on: ubuntu-latest
+    needs:
+      - requirments
 
     steps:
       - name: Checkout
